server:
  port: 8091
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_URI}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true